In [1]:
class ArrayStack:
    def __init__(self):
        self.bucket = []
        
    def push(self, data):
        self.bucket.append(data)
        
    def pop(self):
        return self.bucket.pop()
    
    def size(self):
        return len(self.bucket)
    
    def is_empty(self):
        return self.size() == 0
    
    def display(self):
        print(self.bucket)
        


In [2]:
stack = ArrayStack()
type(stack)

__main__.ArrayStack

In [3]:
stack.push("vineet")
stack.push("sonu")
stack.push("anonymous")
stack.display()

['vineet', 'sonu', 'anonymous']


In [4]:
stack.pop()

'anonymous'

In [13]:
stack.size()

2

In [21]:
from collections import deque
class Que:
    def __init__(self):
        self.bucket = deque()
        
    def enqueData(self, data):
        self.bucket.append(data)
        
    def dequeData(self):
        return self.bucket.popleft()
    
    def size(self):
        return len(self.bucket)
    
    def is_empty(self):
        return self.size() == 0
    
    def display(self):
        print(self.bucket)

In [22]:
q = Que()
q.enqueData("A")
q.enqueData("B")
q.dequeData()

'A'

In [117]:
class Node:
    def __init__(self, xdata):
        self.data = xdata
        self.next = None
        
    def get_data(self):
        return self.data
    
    def set_data(self, newData):
        self.data = newData
        
    def set_next(self, newNext):
        self.next = newNext
        
    def get_next(self):
        return self.next;
    
    def __str__(self):
        return str(self.data)

In [118]:
node = Node(5)
print(node)

5


In [213]:
class UnorderedList:
    def __init__(self):
        self.head = None
        
    def is_empty(self):
        return self.head == None
    
    def add(self, data):
        newNode = Node(data)
        newNode.set_next(self.head)
        self.head = newNode
        
    def size(self):
        current = self.head
        count = 0;
        while current != None:
            count = count + 1
            current = current.get_next()
            
        return count
    
    def search(self, item):
        current = self.head
        found = False
        while current != None and not found:
            if current.get_data() == item:
                found = True
            else:
                current = current.get_next()
                
        return found
    
    def remove(self,item):
        current = self.head
        previous = None
        found = False
        while not found:
            if current.get_data() == item:
                found = True
            else:
                previous = current
                current = current.get_next()

        if previous == None:
            self.head = current.get_next()
        else:
            previous.set_next(current.get_next())
            
    def index(self, item):
        current = self.head
        count = 0;
        found = False
        while current != None and not found:
            if current.get_data() == item:
                found = True
            else:
                current = current.get_next()
                count = count + 1
        return count
            
    def append(self, item):
        current = self.head
        previous = None
        while current != None:
            previous = current
            current = current.get_next()
            
        if type(item) == 'list':
            for i in item:
                n = Node(i)
                previous.set_next(n)
                n = previous
                
        else:
            newNode = Node(item)
            previous.set_next(newNode)
        
    def pop(self):
        poppedNode = self.head
        if self.size() > 1:
            self.head.set_next(self.head.get_next().get_next())
        else:
            self.head.set_next(None)
        return poppedNode.get_data()
        

In [184]:
ul = UnorderedList()
ul.add("a")
ul.add("b")
ul.add("c")
ul.add("d")
ul.append("e")
print(ul.index("a"))
print(ul.index("b"))
print(ul.index("c"))
print(ul.index("d"))
print(ul.index("e"))
ul.append(["1", "2", "3", "4", "5"])

3
2
1
0
4


In [183]:
ul.size()

6

In [167]:
ul.search("b")

True

In [95]:
class Node:
    def __init__(self, data=None):
        self.left = None
        self.right = None
        self.data = data
    def set_left(self, l):
        self.left = l
    def set_right(self, r):
        self.right = r
    def set_data(self, data):
        self.data = data
    def get_left(self):
        return self.left
    def get_right(self):
        return self.right
    def get_data(self):
        return self.data

In [111]:
class BTree:
    def __init__(self):
        self.root = Node()
    def add(self, data):
        xNode = Node()
        xNode.set_data(data)
        if self.root.data == None:
            self.root = xNode
        else:
            self._add(data, self.root)
        
    def _add(self, data, n):
        if data < n.get_data():
            if n.get_left() != None:
                self._add(data, n.get_left())
            else:
                n.set_left(Node(data))
        else:
            if n.get_right() != None:
                self._add(data, n.get_right())
            else:
                n.set_right(Node(data))
                
    def get_root(self):
        return self.root
    
    def display(self, n):
        if n != None:
            print(n.get_data())
            self.display(n.get_left())
            self.display(n.get_right())    

In [112]:
b = BTree()
b.add(9)
b.add(2)
b.add(5)
b.add(1)
b.display(b.get_root())

9
2
1
5


In [113]:
from numpy import matrix
m = matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
class Graph:
    
    def __init__(self, dic = None, directed = True): 
        self.dic = {}
        self.directed = directed
        if not directed: self.create_undirected()
    def create_undirected(self):
        for a in self.dic.keys():
            for (b, distance) in self.dic[a].items():
                self.connect_1(b, a, distance)
    def connect(self, A, B, distance=1):
        self.connect_1(A, B, distance)
        if not self.directed: self.connect_1(B, A, distance)
    def connect_1(self, A, B, distance): 
        self.dic.setdefault(A, {})[B] = distance
    def get(self, a, b=None):
        links = self.dic.setdefault(a, {})
        if b is None: return links
        else: return links.get(b)
    def nodes(self):
        return self.dic.keys()
    

In [8]:
graph = Graph()
graph.connect(1, 3)
graph.connect(1, 2)
graph.connect(1, 4)
graph.connect(2, 3)
graph.connect(2, 5)
print(graph.get(1))
print(graph.get(2))
print(graph.nodes())

{2: 1, 3: 1, 4: 1}
{3: 1, 5: 1}
dict_keys([1, 2])
